# Generated by Django 5.2.3 on 2025-06-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_alter_turma_alunos_alter_turma_tutor'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
