# Generated by Django 5.2.3 on 2025-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('materia', models.SmallIntegerField(choices=[(0, 'Outra'), (1, 'Matemática'), (2, 'Línguas'), (3, 'História'), (4, 'Geografia'), (5, 'Ciências naturais'), (6, 'Esportes'), (7, 'Arte e Design'), (8, 'Computação')])),
                ('alunos', models.ManyToManyField(related_name='alunos_turma', to='users.perfil')),
                ('propriedades', models.ManyToManyField(to='turma.propriedade')),
                ('tutor', models.ManyToManyField(related_name='tutor_turma', to='users.perfil')),
            ],
        ),
    ]
