# Generated by Django 5.2.3 on 2025-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_atividade_aula_aviso_turma_atividades_turma_aulas_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='alunos_turma', to='users.perfil'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='propriedades',
            field=models.ManyToManyField(blank=True, to='turma.propriedade'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tutor',
            field=models.ManyToManyField(blank=True, related_name='tutor_turma', to='users.perfil'),
        ),
    ]
