# Generated by Django 5.2.3 on 2025-06-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('turma', '0003_alter_turma_alunos_alter_turma_propriedades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='alunos_turma', to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tutor',
            field=models.ManyToManyField(blank=True, related_name='tutor_turma', to='perfil.perfil'),
        ),
    ]
