# Generated by Django 5.2 on 2025-06-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_alter_turma_alunos_alter_turma_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='data_entrega',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='data_aula',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aviso',
            old_name='data_publicacao',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='funcao',
        ),
        migrations.AddField(
            model_name='propriedade',
            name='privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='ranking',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='avisos',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='propriedades',
        ),
        migrations.AddField(
            model_name='turma',
            name='avisos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.aviso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='propriedades',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.propriedade'),
        ),
    ]
