# Generated by Django 5.2.3 on 2025-06-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_endereco_remove_perfil_telefone'),
        ('turma', '0005_rename_data_entrega_atividade_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='aluno_turma', to='perfil.perfil'),
        ),
    ]
