# Generated by Django 5.2.3 on 2025-06-14 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0006_aula_titulo_alter_atividade_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='aulas',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='avisos',
        ),
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='presenca',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='turma/fotos'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aviso',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.turma'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='turma/fotos'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
