# Generated by Django 5.2.3 on 2025-06-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0007_remove_aula_conteudo_remove_aviso_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='descricao',
            field=models.TextField(),
        ),
    ]
